name: "Type-check"
description: "Type-check the project using TSC"

runs:
  using: composite
  steps:
    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: 1.1.27

    - shell: bash
      run: bun install --frozen-lockfile

    - shell: bash
      run: bun run typecheck
