export const env = {
  NODE_ENV: process.env.NODE_ENV,
  RESEND_API_KEY: process.env.RESEND_API_KEY,
  GOOD_DOG_FROM_EMAIL: process.env.GOOD_DOG_FROM_EMAIL,
  VERCEL_ENV: process.env.VERCEL_ENV,
  VERCEL_URL: process.env.VERCEL_URL,
  SUPABASE_URL: process.env.SUPABASE_URL,
  SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY,
  SUPABASE_GALLERY_STORAGE_BUCKET: process.env.SUPABASE_GALLERY_STORAGE_BUCKET,
};
