name: Apply Database Migrations

on:
  push:
    branches:
      - main

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/bun

      - name: Apply Migrations
        env:
          DATABASE_PRISMA_URL: ${{ secrets.DATABASE_PRISMA_URL }}
        run: bun db:migrate:prod
