name: Apply Database Migrations

on:
  push:
    branches:
      - main

jobs:
  migrate:
    runs-on: ubuntu-latest
    env:
      DATABASE_PRISMA_URL: ${{ secrets.DATABASE_PRISMA_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-bun

      - name: Apply Migrations
        run: bun prisma migrate deploy --schema=./packages/db/prisma/schema.prisma
