name: Run Bun Tests

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DATABASE_PRISMA_URL: postgres://user:password@localhost:5432/test_db

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-bun

      - name: Apply database schema
        run: |
          bun prisma db push \
          --schema=./packages/db/prisma/schema.prisma

      - name: Run tests
        run: bun test

      - name: Verify database is empty
        env:
          PG_PASSWORD: password
          PG_DB: test_db
        run: |
          sudo apt-get install -y postgresql-client
          chmod +x ./.github/scripts/verify_db_empty.sh
          ./.github/scripts/verify_db_empty.sh
