name: Check Database Migrations

on:
  pull_request:

jobs:
  check-migrations:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: shadow_db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - uses: ./.github/actions/setup-bun

      - name: Check migrations
        env:
          SHADOW_DATABASE_PRISMA_URL: postgres://user:password@localhost:5432/shadow_db
        run: |
          bun prisma migrate diff \
          --config ./packages/db/prisma.config.ts \
          --exit-code \
          --from-migrations ./packages/db/prisma/migrations \
          --to-schema ./packages/db/prisma/schema.prisma
