name: Apply Preview Database Migrations

on:
  workflow_dispatch:
  push:

jobs:
  apply-preview-migrations:
    runs-on: ubuntu-latest
    env:
      DATABASE_PRISMA_URL: ${{ secrets.PREVIEW_DATABASE_PRISMA_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.27

      - name: Apply Changes
        run: |
          bunx prisma db push \
            --schema=./packages/db/prisma/schema.prisma \
            --accept-data-loss \
            --skip-generate
