name: Reset Production Database (No Seeding)

on:
  workflow_dispatch:

jobs:
  reset-production-database:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-bun

      - name: Reset Production Database (No Seeding)
        run: bun prisma migrate reset --skip-seed --force
        working-directory: packages/db
        env:
          DATABASE_PRISMA_URL: ${{ secrets.DATABASE_PRISMA_URL }}
