name: Seed Preview Database

on:
  workflow_dispatch:

jobs:
  apply-preview-migrations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-bun

      - name: Reset and Seed Preview Database
        run: bun prisma migrate reset --force --schema ./packages/db/prisma/schema.prisma
        env:
          DATABASE_PRISMA_URL: ${{ secrets.PREVIEW_DATABASE_PRISMA_URL }}
